### ISSUE TITLE
Android api 29 will crash

### ISSUE THREAD

**Issue by guijia162** [TinloneX/MyReplugin#1]
when i use replugin in api 29, and implement of androidx,my app will crash, and it show "ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList", have you meet this? thks.

**Comment by TinloneX** [comment]
I has no idea on this for now,but I will try it later(this weekend) and update README file, there is Repugin source project issuss link(https://github.com/Qihoo360/RePlugin/issues/768),   maybe can help you.

**Comment by TinloneX** [comment]
my demo has migrate to androidx,  it`s worked ok. I has no device on api29 for reappear this issues.sorry,i cann`t help u.
